name: Google Cloud Storage

on:
  push:
    branches:
    - main

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_KEY }}

    - name: Deploy
      working-directory: ./site
      run: |
        gsutil cp -r . gs://nodematic.com
        gsutil web set -m index.html -e 404.html gs://nodematic.com